/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-10-08 08:31:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style media=\"screen\">\r\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Roboto:300);\r\n");
      out.write("\r\n");
      out.write(".login-page {\r\n");
      out.write("\twidth: 360px;\r\n");
      out.write("\tpadding: 8% 0 0;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tbackground: #FFFFFF;\r\n");
      out.write("\tmax-width: 360px;\r\n");
      out.write("\tmargin: 0 auto 100px;\r\n");
      out.write("\tpadding: 45px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbox-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0\r\n");
      out.write("\t\trgba(0, 0, 0, 0.24);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form input {\r\n");
      out.write("\tfont-family: \"Roboto\", sans-serif;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tbackground: #f2f2f2;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tmargin: 0 0 15px;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form button {\r\n");
      out.write("\tfont-family: \"Roboto\", sans-serif;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tbackground: #4CAF50;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\t-webkit-transition: all 0.3 ease;\r\n");
      out.write("\ttransition: all 0.3 ease;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form button:active, .form button:focus, .form button:hover {\r\n");
      out.write("\tbackground: #43A047;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form .message {\r\n");
      out.write("\tmargin: 15px 0 0;\r\n");
      out.write("\tcolor: #b3b3b3;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form .message a {\r\n");
      out.write("\tcolor: #4CAF50;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form .register-form {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tmax-width: 300px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container:after, .container:before {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .info {\r\n");
      out.write("\tmargin: 50px auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .info h1 {\r\n");
      out.write("\tmargin: 0 0 15px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tfont-size: 36px;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tcolor: #1a1a1a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .info span {\r\n");
      out.write("\tcolor: #4d4d4d;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .info span a {\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .info span .fa {\r\n");
      out.write("\tcolor: #EF3B3A;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: #76b852;\r\n");
      out.write("\t/* fallback for old browsers */\r\n");
      out.write("\tbackground: -webkit-linear-gradient(right, #76b852, #8DC26F);\r\n");
      out.write("\tbackground: -moz-linear-gradient(right, #76b852, #8DC26F);\r\n");
      out.write("\tbackground: -o-linear-gradient(right, #76b852, #8DC26F);\r\n");
      out.write("\tbackground: linear-gradient(to left, #76b852, #8DC26F);\r\n");
      out.write("\tfont-family: \"Roboto\", sans-serif;\r\n");
      out.write("\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\t-moz-osx-font-smoothing: grayscale;\r\n");
      out.write("}\r\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"login-page\">\n");
      out.write("\t<h3>Login Form</h3>\n");
      out.write("\t<h5>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\n");
      out.write("\t\t<div class=\"form\">\n");
      out.write("\t\t\t<form class=\"register-form\">\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"name\" /> <input type=\"password\"\n");
      out.write("\t\t\t\t\tplaceholder=\"password\" /> <input type=\"text\"\n");
      out.write("\t\t\t\t\tplaceholder=\"email address\" />\n");
      out.write("\t\t\t\t<button>create</button>\n");
      out.write("\t\t\t\t<p class=\"message\">\n");
      out.write("\t\t\t\t\tAlready registered? <a href=\"#\">Sign In</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<form class=\"login-form\" action=\"\" method=\"post\">\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"id\" name=\"id\"/>\n");
      out.write("\t\t\t\t<input type=\"password\" placeholder=\"password\" name=\"pw\"/>\n");
      out.write("\t\t\t\t<button type=\"submit\">login</button>\n");
      out.write("\t\t\t\t<p class=\"message\">\n");
      out.write("\t\t\t\t\tNot registered? <a href=\"#\">Create an account</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js\"\n");
      out.write("\t\tcharset=\"utf-8\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("          $('.message a').click(function () {\r\n");
      out.write("            $('form').animate({\r\n");
      out.write("              height: \"toggle\",\r\n");
      out.write("              opacity: \"toggle\"\r\n");
      out.write("            }, \"slow\");\r\n");
      out.write("          });\r\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
